routes/web.php
        ->name('password');
    Route::get('notifications', [UserController::class, 'notifySettings'])
        ->name('notifications');
    Route::get('integrations', [UserController::class, 'integrationsSettings'])
        ->name('integrations');
    Route::get('api', [UserController::class, 'apiSettings'])
        ->name('api');
    Route::get('sessions', [UserController::class, 'sessionsSettings'])
        ->name('sessions');
    Route::get('logs', [UserController::class, 'logsSettings'])
        ->name('logs');
    Route::get('data', [UserController::class, 'dataSettings'])
        ->name('data');
    Route::get('delete', [UserController::class, 'deleteSettings'])
        ->name('delete');
    Route::get('export/account', [UserController::class, 'exportAccount'])
        ->name('export.account');
    Route::get('export/logs', [UserController::class, 'exportLogs'])
        ->name('export.logs');
});

// Notifications
Route::group([
    'prefix' => 'notifications',
    'as' => 'notifications.',
    'middleware' => ['auth'],
], function () {
    Route::view('', 'notifications.unread')
        ->name('unread');
    Route::view('all', 'notifications.all')
        ->name('all');
});

// Webhooks
Route::group(['prefix' => 'webhook'], function () {
    Route::post('web/{token}', [WebhookController::class, 'web']);
});

// Product
Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', [ProductController::class, 'profile'])
        ->name('done');
    Route::get('pending', [ProductController::class, 'profile'])
        ->name('pending');
    Route::get('updates', [ProductController::class, 'profile'])
        ->name('updates');
    Route::get('subscribers', [ProductController::class, 'profile'])
        ->name('subscribers');
    Route::get('edit', [ProductController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('verify', [ProductController::class, 'verify'])
        ->middleware('auth')
        ->name('verify');
});

// Products
Route::group([
    'prefix' => 'products',
    'as' => 'products.',
], function () {
    Route::get('', [ProductController::class, 'newest'])
        ->name('newest');
    Route::get('launched', [ProductController::class, 'launched'])
        ->name('launched');
    Route::view('new', 'products.new')
        ->middleware('auth')
        ->name('new');
});

// Question
Route::group([
    'prefix' => 'question',
    'as' => 'question.',
], function () {
    Route::get('{id}', [QuestionController::class, 'question'])
        ->name('question');
    Route::get('{question}/edit', [QuestionController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
});

// Questions
Route::group([
    'prefix' => 'questions',
    'as' => 'questions.',
], function () {
    Route::get('', [QuestionController::class, 'newest'])
        ->name('newest');
    Route::get('unanswered', [QuestionController::class, 'unanswered'])
        ->name('unanswered');
    Route::get('popular', [QuestionController::class, 'popular'])
        ->name('popular');
    Route::view('new', 'question.new')
        ->middleware('auth')
        ->name('new');
});

// Milestone
Route::group([
    'prefix' => 'milestones',
    'as' => 'milestones.',
], function () {
    Route::get('', [MilestoneController::class, 'opened'])
        ->name('opened');
    Route::get('closed', [MilestoneController::class, 'closed'])
        ->name('closed');
    Route::view('new', 'milestone.new')
        ->middleware('auth')
        ->name('new');
    Route::get('{milestone}/edit', [MilestoneController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('{milestone}', [MilestoneController::class, 'milestone'])
        ->name('milestone');
});

// Search
Route::group([
    'prefix' => 'search',
    'as' => 'search.',
], function () {
    Route::get('', [SearchController::class, 'search'])
        ->name('home');
    Route::get('tasks', [SearchController::class, 'tasks'])
        ->name('tasks');
    Route::get('comments', [SearchController::class, 'comments'])
        ->name('comments');
    Route::get('questions', [SearchController::class, 'questions'])
        ->name('questions');
    Route::get('answers', [SearchController::class, 'answers'])
        ->name('answers');
    Route::get('products', [SearchController::class, 'products'])
        ->name('products');
    Route::get('users', [SearchController::class, 'users'])
        ->name('users');
});

// Stafftools
Route::group([
    'prefix' => 'stafftools',
    'as' => 'staff.',
    'middleware' => ['staff_mode'],
], function () {
    Route::view('', 'staff.stats')
        ->middleware('password.confirm')
        ->name('stats');
    Route::view('users', 'staff.users')
        ->middleware('password.confirm')
        ->name('users');
    Route::view('tasks', 'staff.tasks')
        ->middleware('password.confirm')
        ->name('tasks');
    Route::view('activities', 'staff.activities')
        ->middleware('password.confirm')
        ->name('activities');
    Route::view('products', 'staff.products')
        ->middleware('password.confirm')
        ->name('products');
    Route::view('features', 'staff.features')
        ->middleware('password.confirm')
        ->name('features');
    Route::get('system', [StaffController::class, 'system'])
        ->middleware('password.confirm')
        ->name('system');
    Route::view('jobs', 'staff.jobs')
        ->middleware('password.confirm')
        ->name('jobs');
    Route::view('deployments', 'staff.deployments')
        ->middleware('password.confirm')
        ->name('deployments');
});

// Patron
Route::group([
    'prefix' => 'patron',
    'as' => 'patron.',
], function () {
    Route::view('', 'pages.patron')
        ->name('home');
});

// Paddle Integration
Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])
    ->name('paddle.webhook');

// Dark mode
Route::get('darkmode', [UserController::class, 'darkMode'])
    ->name('darkmode')
    ->middleware('auth');

// Single Task and comment
Route::group(['prefix' => 'task'], function () {
    Route::get('{id}', [TaskController::class, 'task'])
        ->name('task');
    Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])
        ->name('comment');
});

// Zen mode tasks
Route::view('tasks', 'tasks.tasks')
    ->name('tasks')
    ->middleware('auth');

// Meetups
Route::group([
    'prefix' => 'meetups',
    'as' => 'meetups.',
], function () {
    Route::get('/', [MeetupController::class, 'meetups'])
        ->middleware('staff')
        ->name('home');
    Route::get('/rsvpd', [MeetupController::class, 'rsvpd'])
        ->middleware('staff')
        ->name('rsvpd');
    Route::get('/finished', [MeetupController::class, 'finished'])
        ->middleware('staff')
        ->name('finished');
});

// Pages
Route::get('about', [PagesController::class, 'about'])
    ->name('about');
Route::view('terms', 'pages.terms')
    ->name('terms');
Route::view('privacy', 'pages.privacy')
    ->name('privacy');
Route::view('security', 'pages.security')
    ->name('security');
Route::view('sponsors', 'pages.sponsors')
    ->name('sponsors');
Route::view('contact', 'pages.contact')
    ->name('contact');
Route::view('reputation', 'pages.reputation')
    ->name('reputation')
    ->middleware('auth');
Route::view('open', 'pages.open')
    ->name('open');
Route::view('api', 'pages.api')
    ->middleware('feature:api')
    ->name('api');
Route::get('deals', [PagesController::class, 'deals'])
    ->name('deals');

// Status
Route::group(['prefix' => 'status'], function () {
    Route::get('ping', [StatusController::class, 'ping']);
    Route::get('redis', [StatusController::class, 'redis']);
    Route::get('cache', [StatusController::class, 'redisCache']);
});

// Feed
Route::group([
    'prefix' => 'feed',
    'as' => 'feed.',
], function () {
    Route::get('user/{username}/{page?}', [FeedController::class, 'user'])
        ->name('user');
    Route::get('product/{slug}/{page?}', [FeedController::class, 'product'])
        ->name('product');
});

// Mention
Route::group([
    'prefix' => 'mention',
    'middleware' => ['auth'],
], function () {
    Route::get('users', [UserController::class, 'mention']);
    Route::get('products', [ProductController::class, 'mention']);
});

// Popover
Route::group(['prefix' => 'popover'], function () {
    Route::get('user/{user}', [UserController::class, 'popover']);
    Route::get('product/{product}', [ProductController::class, 'popover']);
    Route::get('milestone/{milestone}', [MilestoneController::class, 'popover']);
});

// Site
Route::group(['prefix' => 'site'], function () {
    Route::view('shortcuts', 'site.shortcuts')
        ->name('shortcuts');
    Route::get('commit-data', [StaffController::class, 'commitData'])
        ->middleware('staff_mode')
        ->name('commit-data');
    Route::get('ci-data', [StaffController::class, 'ciData'])
        ->middleware('staff_mode')
        ->name('ci-data');
    Route::get('deployment-data', [StaffController::class, 'deploymentData'])
        ->middleware('staff_mode')
        ->name('deployment-data');
    Route::get('staffbar', [StaffController::class, 'toggle'])
        ->middleware('staff')
        ->name('staffbar');
});

// Sitemaps
Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
Route::get('sitemap_milestones.txt', [SitemapController::class, 'milestones']);
Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

// https://web.dev/change-password-url
Route::get('.well-known/change-password', function () {

app/Http/Livewire/Comment/Comments.php
<?php

namespace App\Http\Livewire\Comment;

use App\Models\Task;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Comments extends Component
{
    public $listeners = [
        'refreshComments' => 'render',
    ];

    public Task $task;
    public $page;
    public $perPage;
    public $readyToLoad = false;

    public function mount($task, $page, $perPage)
    {
        $this->task = $task;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function loadComments()
    {
        $this->readyToLoad = true;
    }

    public function getComments()
    {
        return $this->task->comments()
            ->whereHas('user', function ($q) {
                $q->where([
                    ['spammy', false],
                ]);
            })
            ->oldest()
            ->get();
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        return view('livewire.comment.comments', [
            'comments' => $this->readyToLoad ? $this->paginate($this->getComments()) : [],
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/Comment/CreateComment.php
<?php

namespace App\Http\Livewire\Comment;

use App\Gamify\Points\CommentCreated;
use App\Models\Task;
use App\Notifications\Comment\Commented;
use Helper;
use Illuminate\Support\Facades\Gate;
use Livewire\Component;

class CreateComment extends Component
{
    public $comment = '';
    public Task $task;

    protected $rules = [
        'comment' => ['required', 'min:3', 'max:20000'],
        'task' => ['required'],
    ];

    public function mount($task)
    {
        $this->task = $task;
    }

    public function updated($field)
    {
        if (! auth()->check()) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        $this->validateOnly($field);
    }

    public function submit()
    {
        if (Gate::denies('create')) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        $this->validate();

        $users = Helper::getUsernamesFromMentions($this->comment);

        if ($users) {
            $this->comment = Helper::parseUserMentionsToMarkdownLinks($this->comment, $users);
        }

        $comment = auth()->user()->comments()->create([
            'task_id' => $this->task->id,
            'comment' => $this->comment,
        ]);
        auth()->user()->touch();
        $this->emit('refreshComments');

        $this->reset('comment');
        Helper::mentionUsers($users, $comment, auth()->user(), 'comment');
        Helper::notifySubscribers($comment->task->subscribers, $comment, 'comment');
        if (auth()->user()->id !== $this->task->user->id) {
            if (! auth()->user()->hasSubscribed($comment->task)) {
                auth()->user()->subscribe($comment->task);
                $this->emit('refreshTaskSubscribed');
            }
            $this->task->user->notify(new Commented($comment));
            givePoint(new CommentCreated($comment));
        }
        loggy(request(), 'Comment', auth()->user(), "Created a new comment | Comment ID: {$comment->id}");

        return toast($this, 'success', 'Comment has been added!');
    }

    public function render()
    {
        return view('livewire.comment.create-comment');
    }
}

app/Http/Livewire/Comment/LoadMore.php
<?php

namespace App\Http\Livewire\Comment;

use App\Models\Task;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public Task $task;
    public $page;
    public $perPage;
    public $loadMore;
    public $readyToLoad = true;

    public function mount($task, $page = 1, $perPage = 1)
    {
        $this->task = $task;
        $this->page = $page + 1;
        $this->perPage = $perPage;
        $this->loadMore = false;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            $comments = $this->task->comments()
                ->whereHas('user', function ($q) {
                    $q->where([
                        ['spammy', false],
                    ]);
                })
                ->orderBy('created_at', 'DESC')
                ->get();

            return view('livewire.comment.comments', [
                'comments' => $this->paginate($comments),
            ]);
        }

        return view('livewire.load-more');
    }
}

app/Http/Livewire/Comment/Reply/Replies.php
<?php

namespace App\Http\Livewire\Comment\Reply;

use App\Models\Comment;
use Livewire\Component;

class Replies extends Component
{
    public $listeners = [
        'refreshReplies' => 'render',
    ];

    public Comment $comment;

    public function render()
    {
        return view('livewire.comment.reply.replies');
    }
}

app/Http/Livewire/Comment/Reply/SingleReply.php
<?php

namespace App\Http\Livewire\Comment\Reply;

use App\Models\CommentReply;
use DanHarrin\LivewireRateLimiting\WithRateLimiting;
use Helper;
use Illuminate\Support\Facades\Gate;
use Livewire\Component;

class SingleReply extends Component
{
    use WithRateLimiting;

    public CommentReply $reply;

    public function mount($reply)
    {
        $this->reply = $reply;
    }

    public function toggleLike()
    {
        try {
            $this->rateLimit(50);
        } catch (TooManyRequestsException $exception) {
            return toast($this, 'error', config('taskord.error.rate-limit'));
        }

        if (Gate::denies('like/subscribe', $this->reply)) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        Helper::toggleLike($this->reply, 'REPLY');
        $this->emit('replyLiked');

        return loggy(request(), 'Reply', auth()->user(), "Toggled reply like | Reply ID: {$this->reply->id}");
    }

    public function deleteReply()
    {
        if (Gate::denies('edit/delete', $this->reply)) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        loggy(request(), 'Reply', auth()->user(), "Deleted a reply | Reply ID: {$this->reply->id}");
        $this->reply->delete();
        $this->emit('refreshReplies');
        auth()->user()->touch();

        return toast($this, 'success', 'Reply has been deleted successfully!');
    }

    public function hide()
    {
        if (Gate::denies('staff.ops')) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        Helper::hide($this->reply);
        loggy(request(), 'Staff', auth()->user(), "Toggled hide reply | Reply ID: {$this->reply->id}");

        return toast($this, 'success', 'Reply is hidden from public!');
    }
}

resources/views/livewire/comment/reply/create-reply.blade.php
<div class="card {{ $comment->replies()->count('id') > 0 ? '' : 'mt-3' }}">
    <div x-data="{ tab: 'edit' }">
        <div class="pt-2 rounded-top bg-body">
            <ul class="nav nav-tabs d-flex justify-content-between px-3">
                <div class="d-flex">
                    <li class="nav-item">
                        <div class="cursor-pointer nav-link active" :class="{ 'bg-white active': tab === 'edit' }" @click="tab = 'edit'">Edit</div>
                    </li>
                    <li class="nav-item">
                        <div class="cursor-pointer nav-link" :class="{ 'active bg-white': tab === 'preview' }" @click="tab = 'preview'">Preview</div>
                    </li>
                </div>
                <div x-show="tab === 'edit'" class="pt-1">
                    <x:markdown-toolbar htmlFor="reply-box-{{ $comment->id }}" />
                </div>
            </ul>
        </div>
        <div class="card-body">
            @error('reply')
                <div class="alert alert-danger alert-dismissible fade show">
                    <button type="button" class="btn-close small" data-bs-dismiss="alert"></button>
                    <x-heroicon-o-exclamation class="heroicon" />
                    {{ $message }}
                </div>
            @enderror
            <div class="mb-2">
                <textarea x-show="tab === 'edit'" placeholder="Leave a reply" id="reply-box-{{ $comment->id }}" class="form-control mentionInput" rows="3" wire:model.lazy="reply"></textarea>
                <div x-show="tab === 'preview'">
                    <div wire:loading>
                        Loading preview...
                    </div>
                    <div wire:loading.remove>
                        @if ($reply)
                            {!! markdown($reply) !!}
                        @else
                            Nothing to preview...
                        @endif
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <a class="small fw-bold text-secondary" href="https://guides.github.com/features/mastering-markdown" target="_blank">
                    <x-heroicon-o-pencil-alt class="heroicon" />
                    Markdown is supported
                    <x:labels.beta />
                </a>
                <button wire:loading.attr="disabled" wire:target="submit" class="btn btn-sm btn-outline-primary rounded-pill" type="submit" wire:click="submit" @click="tab = 'edit'">
                    <x-heroicon-o-plus class="heroicon heroicon-15px" />
                    Reply
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/comment/reply/replies.blade.php
<div class="{{ $comment->replies->count('id') > 0 ? 'mt-3' : '' }}">
    @if ($comment->replies->count('id') > 0)
        @foreach ($comment->replies as $reply)
            <livewire:comment.reply.single-reply :reply="$reply" :wire:key="$reply->id" />
        @endforeach
    @endif
</div>

resources/views/livewire/comment/reply/single-reply.blade.php
<div id="reply_{{ $reply->id }}">
    <div class="align-items-center d-flex">
        <x:shared.user-label-small :user="$reply->user" />
        <span class="align-text-top small float-end ms-auto text-secondary">
            {{ carbon($reply->created_at)->diffForHumans() }}
        </span>
    </div>
    <div class="border-2 border-start ps-3 reply-line pt-2 pb-3">
        @if ($reply->hidden)
            <span class="body-font fst-italic text-secondary">Reply was hidden by moderator</span>
        @else
            <span class="body-font">
                {!! markdown($reply->reply) !!}
            </span>
        @endif
        <div class="mt-2">
            @auth
                <x:like-button :entity="$reply" />
                @can('edit/delete', $reply)
                    <button
                        type="button"
                        class="btn btn-action btn-outline-danger"
                        onclick="confirm('Are you sure?') || event.stopImmediatePropagation()"
                        wire:click="deleteReply"
                        wire:loading.attr="disabled"
                        wire:target="deleteReply"
                        aria-label="Delete"
                    >
                        <x-heroicon-o-trash class="heroicon heroicon-15px me-0 text-secondary" />
                    </button>
                @endcan
                @can('staff.ops')
                    <button type="button" class="btn btn-action {{ $reply->hidden ? 'btn-info' : 'btn-outline-info' }} ms-1" wire:click="hide" wire:loading.attr="disabled" wire:key="{{ $reply->id }}" aria-label="Hide">
                        <x-heroicon-o-eye-off class="heroicon heroicon-15px me-0" />
                    </button>
                @endcan
            @endauth
        </div>
    </div>
</div>