routes/web.php
<?php

use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Suspended
Route::view('suspended', 'auth.suspended')
    ->name('suspended');

// Home/Dashboard/Landing
Route::view('/', 'home.home')->name('home');

// Explore
Route::group(['prefix' => 'explore', 'as' => 'explore.'], function () {
    Route::view('', 'explore.explore')
        ->name('explore');
    Route::view('/makers', 'explore.makers')
        ->middleware('feature:explore_makers')
        ->name('makers');
});

// User
Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', [UserController::class, 'profile'])
        ->name('done');
    Route::get('pending', [UserController::class, 'profile'])
        ->name('pending');
    Route::get('products', [UserController::class, 'profile'])
        ->name('products');
    Route::get('questions', [UserController::class, 'profile'])
        ->name('questions');
    Route::get('answers', [UserController::class, 'profile'])
        ->name('answers');
    Route::get('milestones', [UserController::class, 'profile'])
        ->name('milestones');
    Route::get('following', [UserController::class, 'profile'])
        ->name('following');
    Route::get('followers', [UserController::class, 'profile'])
        ->name('followers');
    Route::get('stats', [UserController::class, 'profile'])
        ->name('stats');
});

// Settings
Route::group([
    'prefix' => 'settings',
    'as' => 'user.settings.',
    'middleware' => ['auth'],
], function () {
    Route::get('', [UserController::class, 'profileSettings'])
        ->name('profile');
    Route::get('account', [UserController::class, 'accountSettings'])
        ->name('account');
    Route::get('appearance', [UserController::class, 'appearanceSettings'])
        ->name('appearance');
    Route::get('products', [UserController::class, 'productsSettings'])
        ->name('products');
    Route::get('patron', [UserController::class, 'patronSettings'])
        ->name('patron');
    Route::get('password', [UserController::class, 'passwordSettings'])
        ->name('password');
    Route::get('notifications', [UserController::class, 'notifySettings'])
        ->name('notifications');
    Route::get('integrations', [UserController::class, 'integrationsSettings'])
        ->name('integrations');
    Route::get('api', [UserController::class, 'apiSettings'])
        ->name('api');
    Route::get('sessions', [UserController::class, 'sessionsSettings'])
        ->name('sessions');
    Route::get('logs', [UserController::class, 'logsSettings'])
        ->name('logs');
    Route::get('data', [UserController::class, 'dataSettings'])
        ->name('data');
    Route::get('delete', [UserController::class, 'deleteSettings'])
        ->name('delete');
    Route::get('export/account', [UserController::class, 'exportAccount'])
        ->name('export.account');
    Route::get('export/logs', [UserController::class, 'exportLogs'])
        ->name('export.logs');
});

// Notifications
Route::group([
    'prefix' => 'notifications',
    'as' => 'notifications.',
    'middleware' => ['auth'],
], function () {
    Route::view('', 'notifications.unread')
        ->name('unread');
    Route::view('all', 'notifications.all')
        ->name('all');
});

// Webhooks
Route::group(['prefix' => 'webhook'], function () {
    Route::post('web/{token}', [WebhookController::class, 'web']);
});

// Product
Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', [ProductController::class, 'profile'])
        ->name('done');
    Route::get('pending', [ProductController::class, 'profile'])
        ->name('pending');
    Route::get('updates', [ProductController::class, 'profile'])
        ->name('updates');
    Route::get('subscribers', [ProductController::class, 'profile'])
        ->name('subscribers');
    Route::get('edit', [ProductController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('verify', [ProductController::class, 'verify'])
        ->middleware('auth')
        ->name('verify');
});

// Products
Route::group([
    'prefix' => 'products',
    'as' => 'products.',
], function () {
    Route::get('', [ProductController::class, 'newest'])
        ->name('newest');
    Route::get('launched', [ProductController::class, 'launched'])
        ->name('launched');
    Route::view('new', 'products.new')
        ->middleware('auth')
        ->name('new');
});

// Question
Route::group([
    'prefix' => 'question',
    'as' => 'question.',
], function () {
    Route::get('{id}', [QuestionController::class, 'question'])
        ->name('question');
    Route::get('{question}/edit', [QuestionController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
});

// Questions
Route::group([
    'prefix' => 'questions',
    'as' => 'questions.',
], function () {
    Route::get('', [QuestionController::class, 'newest'])
        ->name('newest');
    Route::get('unanswered', [QuestionController::class, 'unanswered'])
        ->name('unanswered');
    Route::get('popular', [QuestionController::class, 'popular'])
        ->name('popular');
    Route::view('new', 'question.new')
        ->middleware('auth')
        ->name('new');
});

// Milestone
Route::group([
    'prefix' => 'milestones',
    'as' => 'milestones.',
], function () {
    Route::get('', [MilestoneController::class, 'opened'])
        ->name('opened');
    Route::get('closed', [MilestoneController::class, 'closed'])
        ->name('closed');
    Route::view('new', 'milestone.new')
        ->middleware('auth')
        ->name('new');
    Route::get('{milestone}/edit', [MilestoneController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('{milestone}', [MilestoneController::class, 'milestone'])
        ->name('milestone');
});

// Search
Route::group([
    'prefix' => 'search',
    'as' => 'search.',
], function () {
    Route::get('', [SearchController::class, 'search'])
        ->name('home');
    Route::get('tasks', [SearchController::class, 'tasks'])
        ->name('tasks');
    Route::get('comments', [SearchController::class, 'comments'])
        ->name('comments');
    Route::get('questions', [SearchController::class, 'questions'])
        ->name('questions');
    Route::get('answers', [SearchController::class, 'answers'])
        ->name('answers');
    Route::get('products', [SearchController::class, 'products'])
        ->name('products');
    Route::get('users', [SearchController::class, 'users'])
        ->name('users');
});

// Stafftools
Route::group([
    'prefix' => 'stafftools',
    'as' => 'staff.',
    'middleware' => ['staff_mode'],
], function () {
    Route::view('', 'staff.stats')
        ->middleware('password.confirm')
        ->name('stats');
    Route::view('users', 'staff.users')
        ->middleware('password.confirm')
        ->name('users');
    Route::view('tasks', 'staff.tasks')
        ->middleware('password.confirm')
        ->name('tasks');
    Route::view('activities', 'staff.activities')
        ->middleware('password.confirm')
        ->name('activities');
    Route::view('products', 'staff.products')
        ->middleware('password.confirm')
        ->name('products');
    Route::view('features', 'staff.features')
        ->middleware('password.confirm')
        ->name('features');
    Route::get('system', [StaffController::class, 'system'])
        ->middleware('password.confirm')
        ->name('system');
    Route::view('jobs', 'staff.jobs')
        ->middleware('password.confirm')
        ->name('jobs');
    Route::view('deployments', 'staff.deployments')
        ->middleware('password.confirm')
        ->name('deployments');
});

// Patron
Route::group([
    'prefix' => 'patron',
    'as' => 'patron.',
], function () {
    Route::view('', 'pages.patron')
        ->name('home');
});

// Paddle Integration
Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])
    ->name('paddle.webhook');

// Dark mode
Route::get('darkmode', [UserController::class, 'darkMode'])
    ->name('darkmode')
    ->middleware('auth');

// Single Task and comment
Route::group(['prefix' => 'task'], function () {
    Route::get('{id}', [TaskController::class, 'task'])
        ->name('task');
    Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])
        ->name('comment');
});

// Zen mode tasks
Route::view('tasks', 'tasks.tasks')
    ->name('tasks')
    ->middleware('auth');

// Meetups
Route::group([
    'prefix' => 'meetups',
    'as' => 'meetups.',
], function () {

app/Http/Livewire/Answer/Answers.php
<?php

namespace App\Http\Livewire\Answer;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Answers extends Component
{
    public $listeners = [
        'refreshAnswers' => 'render',
    ];

    public Question $question;
    public $page;
    public $perPage;
    public $readyToLoad = false;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function loadAnswers()
    {
        $this->readyToLoad = true;
    }

    public function getAnswers()
    {
        return Answer::whereQuestionId($this->question->id)
            ->whereHas('user', function ($q) {
                $q->where([
                    ['spammy', false],
                ]);
            })
            ->orderBy('created_at', 'DESC')
            ->get();
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        return view('livewire.answer.answers', [
            'answers' => $this->readyToLoad ? $this->paginate($this->getAnswers()) : [],
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/Answer/CreateAnswer.php
<?php

namespace App\Http\Livewire\Answer;

use App\Gamify\Points\CommentCreated;
use App\Models\Question;
use App\Notifications\Answer\Answered;
use Helper;
use Illuminate\Support\Facades\Gate;
use Livewire\Component;

class CreateAnswer extends Component
{
    public $answer = '';
    public Question $question;

    protected $rules = [
        'answer' => ['required', 'min:3', 'max:20000'],
    ];

    public function mount($question)
    {
        $this->question = $question;
    }

    public function updated($field)
    {
        $this->validateOnly($field);
    }

    public function submit()
    {
        if (Gate::denies('create')) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        $this->validate();

        $users = Helper::getUsernamesFromMentions($this->answer);

        if ($users) {
            $this->answer = Helper::parseUserMentionsToMarkdownLinks($this->answer, $users);
        }

        $answer = auth()->user()->answers()->create([
            'question_id' => $this->question->id,
            'answer' => $this->answer,
        ]);
        auth()->user()->touch();
        $this->emit('refreshAnswers');

        $this->reset('answer');
        Helper::mentionUsers($users, $answer, auth()->user(), 'answer');
        Helper::notifySubscribers($answer->question->subscribers, $answer, 'answer');
        if (auth()->user()->id !== $this->question->user->id) {
            if (! auth()->user()->hasSubscribed($answer->question)) {
                auth()->user()->subscribe($answer->question);
                $this->emit('refreshQuestionSubscribe');
            }
            $this->question->user->notify(new Answered($answer));
            givePoint(new CommentCreated($answer));
        }
        loggy(request(), 'Answer', auth()->user(), "Created a new answer | Answer ID: {$answer->id}");

        return toast($this, 'success', 'Answer has been added!');
    }

    public function render()
    {
        return view('livewire.answer.create-answer');
    }
}

app/Http/Livewire/Answer/LoadMore.php
<?php

namespace App\Http\Livewire\Answer;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public Question $question;
    public $page;
    public $perPage;
    public $loadMore;
    public $readyToLoad = true;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page + 1;
        $this->perPage = $perPage;
        $this->loadMore = false;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            $answers = Answer::whereQuestionId($this->question->id)
                ->whereHas('user', function ($q) {
                    $q->where([
                        ['spammy', false],
                    ]);
                })
                ->get();

            return view('livewire.answer.answers', [
                'answers' => $this->paginate($answers),
            ]);
        }

        return view('livewire.load-more');
    }
}

app/Http/Livewire/Answer/SingleAnswer.php
<?php

namespace App\Http\Livewire\Answer;

use App\Models\Answer;
use DanHarrin\LivewireRateLimiting\Exceptions\TooManyRequestsException;
use DanHarrin\LivewireRateLimiting\WithRateLimiting;
use Helper;
use Illuminate\Support\Facades\Gate;
use Livewire\Component;

class SingleAnswer extends Component
{
    use WithRateLimiting;

    public Answer $answer;

    public function mount($answer)
    {
        $this->answer = $answer;
    }

    public function toggleLike()
    {
        try {
            $this->rateLimit(50);
        } catch (TooManyRequestsException $exception) {
            return toast($this, 'error', config('taskord.error.rate-limit'));
        }

        if (Gate::denies('like/subscribe', $this->answer)) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        Helper::toggleLike($this->answer, 'ANSWER');
        $this->emit('answerLiked');

        return loggy(request(), 'Answer', auth()->user(), "Toggled answer like | Answer ID: {$this->answer->id}");
    }

    public function hide()
    {
        if (Gate::denies('staff.ops')) {
            return toast($this, 'error', config('taskord.error.deny'));
        }

        Helper::hide($this->answer);
        $this->emit('answersHidden');
        loggy(request(), 'Staff', auth()->user(), "Toggled hide answer | Answer ID: {$this->answer->id}");

        return toast($this, 'success', 'Answer is hidden from public!');
    }

    public function deleteAnswer()
    {
        if (Gate::denies('edit/delete', $this->answer)) {
            return toast($this, 'success', 'Answer has been deleted successfully!');
        }

        loggy(request(), 'Answer', auth()->user(), "Deleted an answer | Answer ID: {$this->answer->id}");
        $this->answer->delete();
        $this->emit('refreshAnswers');

        return auth()->user()->touch();
    }
}

app/Http/Livewire/Comment/Reply/Replies.php
<?php

namespace App\Http\Livewire\Comment\Reply;

use App\Models\Comment;
use Livewire\Component;

class Replies extends Component
{
    public $listeners = [
        'refreshReplies' => 'render',
    ];

    public Comment $comment;

    public function render()
    {
        return view('livewire.comment.reply.replies');
    }
}

resources/views/livewire/explore/popular-tasks.blade.php
<div wire:init="loadPopularTasks">
    @if (!$readyToLoad)
        <div class="card-body text-center mt-3 mb-3">
            <div class="spinner-border taskord-spinner text-secondary mb-3" role="status"></div>
            <div class="h6">
                Loading popular tasks...
            </div>
        </div>
    @endif
    @foreach ($tasks as $task)
        <div class="card mb-3">
            <span class="p-3">
                <livewire:task.single-task :task="$task" :wire:key="$task->id" />
            </span>
        </div>
    @endforeach
    @if ($readyToLoad)
        <div class="text-center">
            <img class="avatar-100 my-3" src="https://ik.imagekit.io/taskordimg/tada_UEF5fl7T3.png" loading=lazy />
            <h4>
                That's everything we found for you, for now.
            </h4>
            <p>
                Come back soon to see what we find next.
            </p>
        </div>
    @endif
</div>

resources/views/livewire/explore/trending-makers.blade.php
<div wire:init="loadTrendingMakers">
    <div class="text-uppercase fw-bold text-secondary pb-2">
        Trending Makers  <x:labels.beta />
    </div>
    <div class="card mb-4">
        <div class="pt-2 pb-2">
        @if (!$readyToLoad)
            <div class="card-body text-center">
                <div class="spinner-border spinner-border-sm taskord-spinner text-secondary" role="status"></div>
            </div>
        @endif
        @foreach ($users as $user)
            <div class="d-flex align-items-center py-1 px-3">
                <a href="{{ route('user.done', ['username' => $user->username]) }}">
                    <img
                        loading=lazy
                        class="rounded-circle avatar-40 mt-1 user-popover"
                        src="{{ Helper::getCDNImage($user->avatar, 160) }}"
                        data-id="{{ $user->id }}"
                        height="40" width="40"
                        alt="{{ $user->username }}'s avatar"
                    />
                </a>
                <span class="ms-3">
                    <a
                        href="{{ route('user.done', ['username' => $user->username]) }}"
                        class="align-text-top text-dark user-popover"
                        data-id="{{ $user->id }}"
                    >
                        <span class="fw-bold">
                            @if ($user->firstname or $user->lastname)
                                {{ $user->firstname }}{{ ' '.$user->lastname }}
                            @else
                                {{ $user->username }}
                            @endif
                            @if ($user->status)
                                <span class="ms-1 small" title="{{ $user->status }}">{{ $user->status_emoji }}</span>
                            @endif
                            @if ($user->is_verified)
                                <x-heroicon-s-badge-check class="heroicon ms-1 text-primary verified" />
                            @endif
                        </span>
                        <div>
                            @if ($user->bio)
                                <span class="small">
                                    {{ $user->bio }}
                                </span>
                            @else
                                <span class="small text-secondary">
                                    {{ '@'.$user->username }}
                                </span>
                            @endif
                        </div>
                    </a>
                </span>
            </div>
        @endforeach
        </div>
    </div>
</div>

resources/views/livewire/explore/user-card.blade.php
<div class="card" wire:init="loadUser">
    @if (!$readyToLoad)
        <div class="card-body text-center">
            <div class="spinner-border spinner-border-sm taskord-spinner text-secondary" role="status"></div>
        </div>
    @else
    <ul class="list-group list-group-flush">
        <li class="list-group-item text-center py-3">
            <a href="{{ route('user.done', ['username' => $user->username]) }}">
                <img
                    loading=lazy
                    class="rounded-circle avatar-100 mt-1 user-popover"
                    src="{{ Helper::getCDNImage($user->avatar) }}"
                    data-id="{{ $user->id }}"
                    height="40" width="40"
                    alt="{{ $user->username }}'s avatar"
                />
            </a>
            <div class="h4 mt-3 text-dark">
                @if ($user->firstname or $user->lastname)
                    {{ $user->firstname }}{{ ' '.$user->lastname }}
                @endif
            </div>
            <div class="h5 text-secondary">
                {{ $user->username }}
            </div>
            <div>
                @if ($user->status)
                    <div class="d-inline-block border border-dark border-1 mt-2 px-2 py-1 rounded text-dark">
                        <span>{{ $user->status_emoji }}</span>
                        <span title="{{ $user->status }}">{{ Str::limit($user->status, '50') }}</span>
                    </div>
                @endif
            </div>
        </li>
        <li class="list-group-item py-3 fw-bold text-primary">
            {{ $user->followings->count('id') }} following
            {{ pluralize('user', $user->followings->count('id')) }}
        </li>
        <li class="list-group-item py-3 fw-bold text-primary">
            {{ $user->tasks()->count('id') }}
            {{ pluralize('task', $user->tasks()->count('id')) }} created
        </li>
    </ul>
    @endif
</div>