routes/web.php
<?php

use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Suspended
Route::view('suspended', 'auth.suspended')
    ->name('suspended');

// Home/Dashboard/Landing
Route::view('/', 'home.home')->name('home');

// Explore
Route::group(['prefix' => 'explore', 'as' => 'explore.'], function () {
    Route::view('', 'explore.explore')
        ->name('explore');
    Route::view('/makers', 'explore.makers')
        ->middleware('feature:explore_makers')
        ->name('makers');
});

// User
Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('', [UserController::class, 'profile'])
        ->name('done');
    Route::get('pending', [UserController::class, 'profile'])
        ->name('pending');
    Route::get('products', [UserController::class, 'profile'])
        ->name('products');
    Route::get('questions', [UserController::class, 'profile'])
        ->name('questions');
    Route::get('answers', [UserController::class, 'profile'])
        ->name('answers');
    Route::get('milestones', [UserController::class, 'profile'])
        ->name('milestones');
    Route::get('following', [UserController::class, 'profile'])
        ->name('following');
    Route::get('followers', [UserController::class, 'profile'])
        ->name('followers');
    Route::get('stats', [UserController::class, 'profile'])
        ->name('stats');
});

// Settings
Route::group([
    'prefix' => 'settings',
    'as' => 'user.settings.',
    'middleware' => ['auth'],
], function () {
    Route::get('', [UserController::class, 'profileSettings'])
        ->name('profile');
    Route::get('account', [UserController::class, 'accountSettings'])
        ->name('account');
    Route::get('appearance', [UserController::class, 'appearanceSettings'])
        ->name('appearance');
    Route::get('products', [UserController::class, 'productsSettings'])
        ->name('products');
    Route::get('patron', [UserController::class, 'patronSettings'])
        ->name('patron');
    Route::get('password', [UserController::class, 'passwordSettings'])
        ->name('password');
    Route::get('notifications', [UserController::class, 'notifySettings'])
        ->name('notifications');
    Route::get('integrations', [UserController::class, 'integrationsSettings'])
        ->name('integrations');
    Route::get('api', [UserController::class, 'apiSettings'])
        ->name('api');
    Route::get('sessions', [UserController::class, 'sessionsSettings'])
        ->name('sessions');
    Route::get('logs', [UserController::class, 'logsSettings'])
        ->name('logs');
    Route::get('data', [UserController::class, 'dataSettings'])
        ->name('data');
    Route::get('delete', [UserController::class, 'deleteSettings'])
        ->name('delete');
    Route::get('export/account', [UserController::class, 'exportAccount'])
        ->name('export.account');
    Route::get('export/logs', [UserController::class, 'exportLogs'])
        ->name('export.logs');
});

// Notifications
Route::group([
    'prefix' => 'notifications',
    'as' => 'notifications.',
    'middleware' => ['auth'],
], function () {
    Route::view('', 'notifications.unread')
        ->name('unread');
    Route::view('all', 'notifications.all')
        ->name('all');
});

// Webhooks
Route::group(['prefix' => 'webhook'], function () {
    Route::post('web/{token}', [WebhookController::class, 'web']);
});

// Product
Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('', [ProductController::class, 'profile'])
        ->name('done');
    Route::get('pending', [ProductController::class, 'profile'])
        ->name('pending');
    Route::get('updates', [ProductController::class, 'profile'])
        ->name('updates');
    Route::get('subscribers', [ProductController::class, 'profile'])
        ->name('subscribers');
    Route::get('edit', [ProductController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('verify', [ProductController::class, 'verify'])
        ->middleware('auth')
        ->name('verify');
});

// Products
Route::group([
    'prefix' => 'products',
    'as' => 'products.',
], function () {
    Route::get('', [ProductController::class, 'newest'])
        ->name('newest');
    Route::get('launched', [ProductController::class, 'launched'])
        ->name('launched');
    Route::view('new', 'products.new')
        ->middleware('auth')
        ->name('new');
});

// Question
Route::group([
    'prefix' => 'question',
    'as' => 'question.',
], function () {
    Route::get('{id}', [QuestionController::class, 'question'])
        ->name('question');
    Route::get('{question}/edit', [QuestionController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
});

// Questions
Route::group([
    'prefix' => 'questions',
    'as' => 'questions.',
], function () {
    Route::get('', [QuestionController::class, 'newest'])
        ->name('newest');
    Route::get('unanswered', [QuestionController::class, 'unanswered'])
        ->name('unanswered');
    Route::get('popular', [QuestionController::class, 'popular'])
        ->name('popular');
    Route::view('new', 'question.new')
        ->middleware('auth')
        ->name('new');
});

// Milestone
Route::group([
    'prefix' => 'milestones',
    'as' => 'milestones.',
], function () {
    Route::get('', [MilestoneController::class, 'opened'])
        ->name('opened');
    Route::get('closed', [MilestoneController::class, 'closed'])
        ->name('closed');
    Route::view('new', 'milestone.new')
        ->middleware('auth')
        ->name('new');
    Route::get('{milestone}/edit', [MilestoneController::class, 'edit'])
        ->middleware('auth')
        ->name('edit');
    Route::get('{milestone}', [MilestoneController::class, 'milestone'])
        ->name('milestone');
});

// Search
Route::group([
    'prefix' => 'search',
    'as' => 'search.',
], function () {
    Route::get('', [SearchController::class, 'search'])
        ->name('home');
    Route::get('tasks', [SearchController::class, 'tasks'])
        ->name('tasks');
    Route::get('comments', [SearchController::class, 'comments'])
        ->name('comments');
    Route::get('questions', [SearchController::class, 'questions'])
        ->name('questions');
    Route::get('answers', [SearchController::class, 'answers'])
        ->name('answers');
    Route::get('products', [SearchController::class, 'products'])
        ->name('products');
    Route::get('users', [SearchController::class, 'users'])
        ->name('users');
});

// Stafftools
Route::group([
    'prefix' => 'stafftools',
    'as' => 'staff.',
    'middleware' => ['staff_mode'],
], function () {
    Route::view('', 'staff.stats')
        ->middleware('password.confirm')
        ->name('stats');
    Route::view('users', 'staff.users')
        ->middleware('password.confirm')
        ->name('users');
    Route::view('tasks', 'staff.tasks')
        ->middleware('password.confirm')
        ->name('tasks');
    Route::view('activities', 'staff.activities')
        ->middleware('password.confirm')
        ->name('activities');
    Route::view('products', 'staff.products')
        ->middleware('password.confirm')
        ->name('products');
    Route::view('features', 'staff.features')
        ->middleware('password.confirm')
        ->name('features');
    Route::get('system', [StaffController::class, 'system'])
        ->middleware('password.confirm')
        ->name('system');
    Route::view('jobs', 'staff.jobs')
        ->middleware('password.confirm')
        ->name('jobs');
    Route::view('deployments', 'staff.deployments')
        ->middleware('password.confirm')
        ->name('deployments');
});

// Patron
Route::group([
    'prefix' => 'patron',
    'as' => 'patron.',
], function () {
    Route::view('', 'pages.patron')
        ->name('home');
});

// Paddle Integration
Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])
    ->name('paddle.webhook');

// Dark mode
Route::get('darkmode', [UserController::class, 'darkMode'])
    ->name('darkmode')
    ->middleware('auth');

// Single Task and comment
Route::group(['prefix' => 'task'], function () {
    Route::get('{id}', [TaskController::class, 'task'])
        ->name('task');
    Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])
        ->name('comment');
});

// Zen mode tasks
Route::view('tasks', 'tasks.tasks')
    ->name('tasks')
    ->middleware('auth');

// Meetups
Route::group([
    'prefix' => 'meetups',
    'as' => 'meetups.',
], function () {

resources/views/pages/about.blade.php
@extends('layouts.app')

@section('pageTitle', 'About ·')
@section('title', 'About ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container col-lg-6">
    <div class="text-center my-5">
        <img class="mb-3" src="https://ik.imagekit.io/taskordimg/logo_8lLu9EPFa.svg" height="70" alt="Taskord Logo">
        <div class="h1">Get things done in public</div>
        <div class="mt-3 h4 lh-sm text-secondary fw-normal" style="letter-spacing:1px">
            Taskord is a community of makers in tech shipping and working together. Makers post their daily tasks and grow a network of supportive, like-minded people.
        </div>
    </div>
</div>
<div class="container font-monospace d-flex justify-content-evenly">
    <div class="text-center">
        <div class="h4">{{ $tasks }}</div>
        <div class="small">Tasks</div>
    </div>
    <div class="text-center">
        <div class="h4">{{ $users }}</div>
        <div class="small">Users</div>
    </div>
    <div class="text-center">
        <div class="h4">{{ $questions }}</div>
        <div class="small">Questions</div>
    </div>
    <div class="text-center">
        <div class="h4">{{ $milestones }}</div>
        <div class="small">Milestones</div>
    </div>
</div>
<div class="container col-3 my-5">
    <div class="card bg-transparent">
        <div class="card-body d-flex justify-content-between align-items-center">
            <div>Follow us on</div>
            <div>
                <a class="me-3" href="https://twitter.com/taskord" target="_blank">
                    <img class="avatar-20" src="https://ik.imagekit.io/taskordimg/icons/twitter_4cXueyhRfH.svg" loading=lazy />
                </a>
                <a class="me-3 href="https://gitlab.com/yo" target="_blank">
                    <img class="avatar-20" src="https://ik.imagekit.io/taskordimg/icons/gitlab_j_ySNAHxP.svg" loading=lazy />
                </a>
                <a href="https://taskord.com/product/taskord" target="_blank">
                    <img class="avatar-20" src="https://ik.imagekit.io/taskordimg/logo_8lLu9EPFa.svg" loading=lazy />
                </a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/api.blade.php
@extends('layouts.app')

@section('pageTitle', 'API ·')
@section('title', 'API ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header py-3">
            <span class="h5">API</span>
            <div>Taskord's Application Program Interface</div>
        </div>
        <div class="card-body">
            <div>
                The Taskord API lets you build third-party apps for Taskord and integrate with existing ones.
            </div>
            <div class="mt-3">
                The API uses GraphQL. It's a relatively new technology that lets you request all the data you need in just one request. If you're unfamiliar with GraphQL we suggest you <a href="https://graphql.org/learn">read up on it first</a>.
            </div>
            <div class="mt-3">
                You can find all documentation and play around using our <a href="/graphiql">GraphiQL instance</a>.
            </div>
            <div class="mt-3">
                Have a look at some <a href="#">Node.js example code</a> that creates a task and then completes it.
            </div>
            <div class="mt-3">
                POST your GraphQL requests to https://taskord.com/graphql
            </div>
            <div class="mt-3">
                The docs are on the right. Click through to Docs to find all types.
            </div>
            <div class="mt-3">
                @auth
                    Get you <a href="{{ route('user.settings.api') }}">API token here</a>.
                @else
                    Sign in to see your personal <a href="{{ route('user.settings.api') }}">API token</a>.
                @endauth
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/contact.blade.php
@extends('layouts.app')

@section('pageTitle', 'Contact ·')
@section('title', 'Contact ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
<div class="row justify-content-center" style="height:70vh">
    <div class="col-lg-7 mt-5">
        @auth
            @php
                $username = "@".auth()->user()->username;
                $email = urlencode(auth()->user()->email);
                $url = "https://tally.so/embed/5mVVam?username=".$username."&email=".$email."&transparentBackground=1";
            @endphp
            <iframe
                src="{{$url}}"
                width="100%"
                height="100%"
                frameborder="0"
                marginheight="0"
                marginwidth="0"
            ></iframe>
        @else
            <iframe
                src="https://tally.so/embed/63lL53?transparentBackground=1"
                width="100%"
                height="100%"
                frameborder="0"
                marginheight="0"
                marginwidth="0"
            ></iframe>
        @endauth
    </div>
</div>
</div>
@endsection

resources/views/pages/deals.blade.php
@extends('layouts.app')

@section('pageTitle', 'Deals ·')
@section('title', 'Deals ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header py-3">
            <span class="h5">Deals</span>
            <div>Discounts and special deals for Taskord members. Only available for patrons.</div>
            <div>
                <a href="https://tally.so/r/63l4o3" target="_blank" rel="noreferrer">Add your product</a>
            </div>
            @can('staff.ops')
                <button type="button" class="mt-2 btn btn-outline-success rounded-pill" data-bs-toggle="modal" data-bs-target="#newQuestionModal">
                    <x-heroicon-o-plus class="heroicon" />
                    Add a Deal
                </button>
                <livewire:pages.create-deal />
            @endcan
        </div>
        <div class="card-body">
            @if (count($deals) === 0)
                <div class="card-body text-center mt-3 mb-3">
                    <x-heroicon-o-gift class="heroicon heroicon-60px text-primary mb-2" />
                    <div class="h4">
                        No deals found
                    </div>
                </div>
            @endif
            @foreach ($deals as $deal)
                <div class="d-flex align-items-center {{ $loop->last ? '' : 'mb-5' }}">
                    <div>
                        <img loading=lazy class="rounded avatar-100" src="{{ $deal->logo }}" height="100" width="100" alt="{{ $deal->name }}'s Logo" />
                    </div>
                    <div class="ms-4">
                        <span class="h4">
                            {{ $deal->name }}
                        </span>
                        <span class="h5">
                            <span class="align-text-top badge bg-success ms-1">{{ $deal->offer }}% OFF</span>
                        </span>
                        <div class="h6 mt-3">{{ $deal->description }}</div>
                        <div class="mt-2">
                            <a href="{{ $deal->website }}" target="_blank">{{ $deal->website }}</a>
                        </div>
                        @auth
                            @if (auth()->user()->is_patron)
                                @if ($deal->coupon)
                                    <div class="mt-2">
                                        Coupon Code
                                        <code class="ms-2 fw-bold">
                                            {{ $deal->coupon }}
                                        </code>
                                    </div>
                                @else
                                    <div class="mt-2 fw-bold">
                                        <a href="{{ $deal->referral }}" target="_blank">
                                            Click here to get your deal
                                        </a>
                                    </div>
                                @endif
                            @else
                                <div class="mt-2">
                                    <a class="text-secondary" href="{{ route('patron.home') }}">You must be a patron to see coupon code.</a>
                                </div>
                            @endif
                        @endauth
                        @guest
                            <div class="mt-2">
                                <a class="text-secondary" href="{{ route('login') }}">Login to view coupon code.</a>
                            </div>
                        @endguest
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/pages/open.blade.php
@extends('layouts.app')

@section('pageTitle', 'Open ·')
@section('title', 'Open ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<div class="container-md">
    <div class="card">
        <div class="card-header py-3">
            <span class="h5">Open</span>
            <div>Analytics of Taskord</div>
        </div>
        <div class="card-body">
            <livewire:pages.open.all-tasks />
            <livewire:pages.open.completed-tasks />
            <livewire:pages.open.reputations />
        </div>
    </div>
</div>
@endsection

resources/views/pages/patron.blade.php
@extends('layouts.app')

@section('pageTitle', 'Patron ·')
@section('title', 'Patron ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="mb-4 text-center">
        <img loading=lazy src="https://ik.imagekit.io/taskordimg/patron_H2bHcQezM.svg" alt="Taskord Patron" width="100" />
    </div>
    <div class="card">
        <div class="card-header py-3">
            <span class="h5">Become a Patron</span>
            <div>Support Taskord by becoming a Patron.</div>
        </div>
        <div class="card-body">
            <div class="row align-items-center font-monospace">
                <div class="col-lg-8">
                    <div class="fw-bold mb-3">You get the following benefits</div>
                    <ul>
                        <li>🌑 Enable Awesome Dark Mode</li>
                        <li>💬 Patrons only discussion to make it more meaningful</li>
                        <li>🔒 Make your tasks private and get personal things done</li>
                        <li>🤝 Show off your support with the Patron badge</li>
                        <li>👍 Fund on-going development of the platform and server fee</li>
                        <li>More coming soon...</li>
                    </ul>
                </div>
                <div class="col-sm d-grid">
                    @auth
                        @if (auth()->user()->is_patron and auth()->user()->patron()->count('id') === 1)
                            <div class="text-center">
                                <div class="h5">
                                    ❤ You are already a patron!
                                </div>
                                <a class="text-primary" href="{{ route('user.settings.patron') }}">
                                    Go to settings
                                </a>
                            </div>
                        @else
                            <a
                                class="paddle_button btn btn-outline-primary rounded-pill"
                                data-theme="none"
                                data-product="619848"
                                data-message="Support $5/month for Taskord!"
                                data-email="{{ auth()->user()->email }}"
                            >
                                Support $5/month
                            </a>
                            <a
                                class="paddle_button btn mt-2 btn-outline-primary rounded-pill"
                                data-theme="none"
                                data-product="621377"
                                data-message="Support $10/month for Taskord!"
                                data-email="{{ auth()->user()->email }}"
                            >
                                Support $10/month
                            </a>
                            <a
                                class="paddle_button btn mt-2 btn-outline-primary rounded-pill"
                                data-theme="none"
                                data-product="621379"
                                data-message="Support $20/month for Taskord!"
                                data-email="{{ auth()->user()->email }}"
                            >
                                Support $20/month
                            </a>
                            <a
                                class="paddle_button btn mt-2 btn-outline-primary rounded-pill"
                                data-theme="none"
                                data-product="621380"
                                data-message="Support $50/month for Taskord!"
                                data-email="{{ auth()->user()->email }}"
                            >
                                Support $50/month
                            </a>
                            <a
                                class="paddle_button btn mt-2 btn-outline-primary rounded-pill"
                                data-theme="none"
                                data-product="629491"
                                data-message="Support $100 onetime for lifetime pro in Taskord!"
                                data-email="{{ auth()->user()->email }}"
                            >
                                Support $100 onetime
                            </a>
                        @endif
                    @endauth
                    @guest
                        <a class="btn mt-2 btn-outline-success rounded-pill" href="{{ route('login') }}">
                            Login to support!
                        </a>
                    @endguest
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.paddle.com/paddle/paddle.js"></script>
<script type="text/javascript">
	Paddle.Setup({ vendor: 120187 });
</script>
@endsection

resources/views/pages/privacy.blade.php
@extends('layouts.app')

@section('pageTitle', 'Privacy ·')
@section('title', 'Privacy ·')
@section('description', 'Get things done socially with Taskord.')
@section('image', '')
@section('url', url()->current())

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header py-3">
            <span class="h5">Privacy Policy</span>
            <div>Web Site Privacy Policy</div>
        </div>
        <div class="card-body">
            <div>
                Taskord built the Taskord app as an Open Source app. This SERVICE is provided by Taskord at no cost and is intended for use as is.
            </div>
            <div>
                This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.
            </div>
            <div>
                If you choose to use our Service, then you agree to the collection and use of information concerning this policy. The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.
            </div>
            <div>
                The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which are accessible at Taskord unless otherwise defined in this Privacy Policy.
            </div>
            <h5 class="mt-4">Information Collection and Use</h5>
            <div>
                For a better experience, while using our Service, we may require you to provide us with certain personally identifiable information. The information that we request will be retained on your device and is not collected by us in any way.
            </div>
            <h5 class="mt-4">Log Data</h5>
            <div>
                We want to inform you that whenever you use my Service, in a case of an error in the app we collect data and information (through third-party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing my Service, the time and date of your use of the Service, and other statistics.
            </div>
            <h5 class="mt-4">Cookies</h5>
            <div>
                Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.
            </div>
            <div>
                This Service does not use these “cookies” explicitly. However, the app may use third-party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.
            </div>
            <h5 class="mt-4">Service Providers</h5>
            <div>
                We may employ third-party companies and individuals due to the following reasons:
            </div>
            <div class="mt-3">
                <ul>
                    <li>To facilitate our Service;</li>
                    <li>To provide the Service on our behalf;</li>
                    <li>To perform Service-related services; or</li>
                    <li>To assist us in analyzing how our Service is used.</li>
                </ul>
            </div>
            <div>
                We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.
            </div>
            <h5 class="mt-4">Security</h5>
            <div>
                We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.
            </div>
            <h5 class="mt-4">Links to Other Sites</h5>
            <div>
                This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by me. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
            </div>
            <h5 class="mt-4">Children’s Privacy</h5>
            <div>
                These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. In the case we discover that a child under 13 has provided me with personal information, we immediately delete all the information related to this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do the necessary actions.
            </div>
            <h5 class="mt-4">Changes to This Privacy Policy</h5>
            <div>
                We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page.
            </div>
            <div>
                This policy was first produced 2020-09-10, and is updated and latest effective as of 2021-06-01.
                {{-- The very first policy 2020-09-10 --}}
                {{-- First "revised" policy 2021-06-01 --}}
            </div>
            <h5 class="mt-4">Contact Us</h5>
            <div>
                If you have any questions or suggestions about our Privacy Policy, do not hesitate to <a href="https://taskord.com/contact">Contact Us</a>.
            </div>
        </div>
    </div>
</div>
@endsection